version: '3'
services:
  notebooks:
    image: pysyft-notebook:latest
    container_name: notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - WORKSPACE_DIR=/notebooks
    networks:
      - grid_default
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/notebooks
      - ./localstorage-trainer:/localstorage-trainer
    # depends_on:
    #   - 'amdex_server'
  gateway:
    image: heurekalabs/grid-gateway:latest
    container_name: grid-gateway
    environment:
      - PORT=5000
      - SECRET_KEY=ineedtoputasecrethere
      - DATABASE_URL=sqlite:///databasegateway.db
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_LOG-FILE=-
    networks:
      - grid_default
    ports:
      - '5000:5000'
  engine1:
    image: turbofan-engine:latest
    container_name: engine1
    environment:
      - GRID_NETWORK_URL=http://grid-gateway:5000
      - ID=gridnode1
      - ADDRESS=http://engine1:3001
      - DATABASE_URL=sqlite:///databaseGridEngine1.db
      - PORT=3001
      - ENGINE_ID=engine1
      - ENGINE_PORT=8001
      - GRID_NODE_ADDRESS=localhost:3001
      - GRID_GATEWAY_ADDRESS=grid-gateway:5000
      - DATA_DIR=/data
      - DATASET_ID=1
      - CYCLE_LENGTH=1
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_TIMEOUT=600
      - GUNICORN_LOG-FILE=-
    depends_on:
      - 'gateway'
    networks:
      - grid_default
    ports:
      - '3001:3001'
      - '8001:8001'
    volumes:
      - ./localstorage-engine1:/data
  engine2:
    image: turbofan-engine:latest
    container_name: engine2
    environment:
      - GRID_NETWORK_URL=http://grid-gateway:5000
      - ID=gridnode2
      - ADDRESS=http://engine2:3002
      - DATABASE_URL=sqlite:///databaseGridEngine2.db
      - PORT=3002
      - ENGINE_ID=engine2
      - ENGINE_PORT=8002
      - GRID_NODE_ADDRESS=localhost:3002
      - GRID_GATEWAY_ADDRESS=grid-gateway:5000
      - DATA_DIR=/data
      - DATASET_ID=2
      - CYCLE_LENGTH=1
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_TIMEOUT=600
      - GUNICORN_LOG-FILE=-
    depends_on:
      - 'gateway'
    networks:
      - grid_default
    ports:
      - '3002:3002'
      - '8002:8002'
    volumes:
      - ./localstorage-engine2:/data
  engine3:
    image: turbofan-engine:latest
    container_name: engine3
    environment:
      - GRID_NETWORK_URL=http://grid-gateway:5000
      - ID=gridnode3
      - ADDRESS=http://engine3:3003
      - DATABASE_URL=sqlite:///databaseGridEngine3.db
      - PORT=3003
      - ENGINE_ID=engine3
      - ENGINE_PORT=8003
      - GRID_NODE_ADDRESS=localhost:3003
      - GRID_GATEWAY_ADDRESS=grid-gateway:5000
      - DATA_DIR=/data
      - DATASET_ID=3
      - CYCLE_LENGTH=1
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_TIMEOUT=600
      - GUNICORN_LOG-FILE=-
    depends_on:
      - 'gateway'
    networks:
      - grid_default
    ports:
      - '3003:3003'
      - '8003:8003'
    volumes:
      - ./localstorage-engine3:/data
  trainer:
    image: turbofan-federated-trainer:latest
    container_name: trainer
    environment:
      - NEW_DATA_THRESHOLD=300
      - GRID_GATEWAY_ADDRESS=grid-gateway:5000
      - SCHEDULER_INTERVAL=10
      - EPOCHS=30
      - DATA_DIR=/data
      - MODEL_DIR=/models
    depends_on:
      - 'gateway'
      - 'engine1'
      - 'engine2'
      - 'engine3'
    networks:
      - grid_default
    volumes:
      - ./localstorage-trainer/data:/data
      - ./localstorage-trainer/models:/models
  amdex_server:
    image: amdex_server:latest
    container_name: amdex_server
    ports:
      - '8081:8081'
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - grid_default
networks:
  grid_default:
    driver: bridge
