version: "3"
services:
  gateway:
    image: heurekalabs/grid-gateway:latest
    container_name: grid-gateway
    environment:
      - PORT=5000
      - SECRET_KEY=ineedtoputasecrethere
      - DATABASE_URL=sqlite:///databasegateway.db
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_LOG-FILE=-
    networks:
      - grid_default
    ports:
      - "5000:5000"
  engine1:
    image: turbofan-engine:latest
    container_name: engine1
    environment:
      - GRID_NETWORK_URL=http://grid-gateway:5000
      - ID=gridnode1
      - ADDRESS=http://engine1:4001
      - DATABASE_URL=sqlite:///databaseGridEngine1.db
      - PORT=4001
      - ENGINE_ID=engine1
      - ENGINE_PORT=8001
      - GRID_NODE_ADDRESS=localhost:4001
      - GRID_GATEWAY_ADDRESS=grid-gateway:5000
      - DATA_DIR=/data
      - DATASET_ID=1
      - CYCLE_LENGTH=1
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_TIMEOUT=600
      - GUNICORN_LOG-FILE=-
    depends_on:
      - "gateway"
    networks:
      - grid_default
    ports:
      - "4001:4001"
      - "8001:8001"
    volumes:
      # - ./localstorage-engine1:/data
      # - ./CMaps:/data
      - ./Datasets:/data
  engine2:
    image: turbofan-engine:latest
    container_name: engine2
    environment:
      - GRID_NETWORK_URL=http://grid-gateway:5000
      - ID=gridnode2
      - ADDRESS=http://engine2:4002
      - DATABASE_URL=sqlite:///databaseGridEngine2.db
      - PORT=4002
      - ENGINE_ID=engine2
      - ENGINE_PORT=8002
      - GRID_NODE_ADDRESS=localhost:4002
      - GRID_GATEWAY_ADDRESS=grid-gateway:5000
      - DATA_DIR=/data
      - DATASET_ID=2
      - CYCLE_LENGTH=1
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_TIMEOUT=600
      - GUNICORN_LOG-FILE=-
    depends_on:
      - "gateway"
    networks:
      - grid_default
    ports:
      - "4002:4002"
      - "8002:8002"
    volumes:
      # - ./localstorage-engine1:/data
      # - ./CMaps:/data
      - ./Datasets:/data
  trainer:
    image: turbofan-federated-trainer:latest
    container_name: trainer
    environment:
      - NEW_DATA_THRESHOLD=300
      - GRID_GATEWAY_ADDRESS=grid-gateway:5000
      - SCHEDULER_INTERVAL=10
      - EPOCHS=30
      - DATA_DIR=/data
      - MODEL_DIR=/models
    depends_on:
      - "gateway"
      - "engine1"
      - "engine2"
    networks:
      - grid_default
    volumes:
      - ./localstorage-trainer/data:/data
      - ./localstorage-trainer/models:/models
networks:
  grid_default:
    driver: bridge
